# Generated by Django 3.2 on 2021-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
